OfferWebSystem/Controllers/OutletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfferWebSystem.EFnClass;
using OfferWebSystem.Models;
namespace OfferWebSystem.Controllers
{
    [SessionExpire]
    public class OutletController : AppBaseController
    {
        // GET: Outlet
        public List<OfferLocOutletMap> oOutletList = null;
        public OfferLocOutletMap oOfferLocOutletMap = null;

        private List<OfferLocOutletMap> GetOutletList()
        {
            var outletList = new List<OfferLocOutletMap>();
            if (IsCurrentUserAdmin())
                outletList = oDBContext.OfferLocOutletMaps.OrderByDescending(t => t.ID).ToList();
            else
                outletList = oDBContext.OfferLocOutletMaps.Where(t => t.UserId == oCurrentUser.ID).OrderByDescending(t => t.ID).ToList();
            return outletList;
        }
        public ActionResult Index()
        {
            var outletIndexModel = new OutletListModel();
            outletIndexModel.IsUserAdmin = IsCurrentUserAdmin();
            outletIndexModel.OutletList = GetOutletList();
            return View(outletIndexModel);
        }

        [HttpGet]
        public ActionResult NewOutlet()
        {
            oCurrentUser = (SysUser)Session["User"];
            var newOutlet = new OfferLocOutletMap();
            newOutlet.IsActive = true;
            newOutlet.UserId = oCurrentUser.ID;
            
            var outletInfo = new OutletDetailModel();
            outletInfo.IsNew = true;
            outletInfo.Outlet = newOutlet;

            ViewBag.LocationList = oDBContext.OfferLocations.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.LocationName.ToString()
            });

            return PartialView("_outletDetailPartial", outletInfo);
        }

        [HttpGet]
        public ActionResult UpdateOutlet(int id)
        {

            var outletInfo = new OutletDetailModel();
            outletInfo.IsNew = false;
            outletInfo.Outlet = oDBContext.OfferLocOutletMaps.FirstOrDefault(t => t.ID == id);

            ViewBag.LocationList = oDBContext.OfferLocations.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.LocationName.ToString()
            });

            return PartialView("_outletDetailPartial", outletInfo);
        }


        [HttpPost]
        public ActionResult InsertOutlet(OutletDetailModel oOutletInfo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (SysUser)Session["User"];
                    var existOutlet = oDBContext.OfferLocOutletMaps.FirstOrDefault(t => t.ID == oOutletInfo.Outlet.ID);

                    if (existOutlet == null)
                    {
                        OfferLocOutletMap oOfferLocOutletMap = oOutletInfo.Outlet;
                        oOfferLocOutletMap.IsActive = true;
                        oOfferLocOutletMap.CreatedBy=oCurrentUser.ID;
                        oOfferLocOutletMap.CreatedOn=DateTime.Now;
                        oDBContext.OfferLocOutletMaps.Add(oOfferLocOutletMap);
                        oDBContext.SaveChanges();
                        TempData["SuccessMsg"] = "Data Saved Successfully";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Data already Exists!!!";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateOutlet(OutletDetailModel oOutletInfo, string chkIsActive)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (SysUser)Session["User"];
                    var existOutlet = oDBContext.OfferLocOutletMaps.FirstOrDefault(t => t.ID == oOutletInfo.Outlet.ID);

                    if (existOutlet != null)
                    {
                        existOutlet.OutletName = oOutletInfo.Outlet.OutletName;
                        existOutlet.OutletAddress = oOutletInfo.Outlet.OutletAddress;
                        existOutlet.LocationID = oOutletInfo.Outlet.LocationID;
                        existOutlet.IsActive = (!string.IsNullOrEmpty(chkIsActive) && chkIsActive.Contains("on")) ? true : false;
                        existOutlet.ModifiedBy = oCurrentUser.ID;
                        existOutlet.ModifiedOn = DateTime.Now;
                        oDBContext.SaveChanges();
                        TempData["SuccessMsg"] = "Data Update Successfully";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Data Not Found!!!";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult GetOutletByLocation(string[] LocationId, string SearchWord)
        {
            
            SearchWord = SearchWord.Trim().ToLower();
            var searchOutletList = new List<OfferLocOutletMap>();
            searchOutletList = GetOutletList();
            if (searchOutletList != null && searchOutletList.Count > 0)
            {
                if (LocationId != null && LocationId.Count() > 0)
                {
                    if (LocationId[0].Contains(','))
                        LocationId = LocationId[0].Split(',');
                    searchOutletList = searchOutletList.Where(t => LocationId.Contains(t.LocationID.ToString())).ToList();
                }
                    

                if (!string.IsNullOrEmpty(SearchWord))
                    searchOutletList = searchOutletList.Where(t => t.OutletName.ToLower().Contains(SearchWord) || t.OutletAddress.ToLower().Contains(SearchWord) || t.OfferLocation.LocationName.ToLower().Contains(SearchWord)).ToList();

                //if (page != null)
                //{
                //    searchOutletList = searchOutletList.Skip((page.Value - 1) * 4).ToList();
                //}
            }

            return PartialView("_outletListPartial", searchOutletList);
        }


    }
}

OfferWebSystem/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfferWebSystem.EFnClass;
using OfferWebSystem.Models;
using System.IO;

namespace OfferWebSystem.Controllers
{
    [SessionExpire]
    public class PostController : AppBaseController
    {
        // GET: Post
        private int pageSize = 4;
        private static string postImagePath = "/Content/ImagePost/";
        private static string defaultImageFileName = "discount_post_default.jpg";
        public SysUser oSysCurrentUser = null;

        private List<OffersInfo> GetOffersInfo()
        {
            var offerList = new List<OffersInfo>();
            if (IsCurrentUserAdmin())
                offerList = oDBContext.OffersInfoes.OrderByDescending(t => t.ID).ToList();
            else
                offerList = oDBContext.OffersInfoes.Where(t => t.CreatedBy == oCurrentUser.ID).OrderByDescending(t => t.ID).ToList();
            return offerList;
        }
        public ActionResult Index(int? page)
        {

            var postList = new OfferPostListModel();
            postList.IsUserAdmin = IsCurrentUserAdmin();
            postList.OffersList = GetOffersInfo();
            return View(postList);
        }


        public ActionResult GetPostDetail(string postId)
        {
            oCurrentUser = (SysUser)Session["User"];
            OffersInfo oOffersInfo = new OffersInfo();
            if (!string.IsNullOrEmpty(postId))
            {
                var enumFeature = Convert.ToInt32(Enumaretion.DBEnumType.OfferFeature);
                var lowFeature = oDBContext.SysEnums.FirstOrDefault(t => t.EnumType == enumFeature && t.EnumName.ToLower().Contains("low")).ID;
                oOffersInfo = oDBContext.OffersInfoes.FirstOrDefault(t => t.ID.ToString() == postId);
                ViewBag.CatList = oDBContext.OfferCategories.Where(t => t.IsActive).Select(x => x).ToList().Select(x => new SelectListItem
                {
                    Value = x.ID.ToString(),
                    Text = x.CategoryName.ToString()
                });
                if (!IsCurrentUserAdmin())
                {
                    ViewBag.LocList = oDBContext.OfferLocOutletMaps.Where(t => t.IsActive && t.SysUser.ID == oCurrentUser.ID).Select(x => x.OfferLocation).Distinct().ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.LocationName.ToString()
                    });
                }
                else
                {
                    ViewBag.LocList = oDBContext.OfferLocOutletMaps.Where(t => t.IsActive).Select(x => x.OfferLocation).Distinct().ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.LocationName.ToString()
                    });
                }

                if (IsCurrentUserAdmin())
                {

                    ViewBag.FeatureList = oDBContext.SysEnums.Where(t => t.EnumType == enumFeature).Select(x => x).Distinct().ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.EnumName.ToString()
                    });
                }
                else
                {
                    ViewBag.FeatureList = oDBContext.SysEnums.Where(t => t.EnumType == enumFeature && t.EnumName.ToLower().Contains("low")).Select(x => x).Distinct().ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.EnumName.ToString()
                    });
                }
            }
            return PartialView("_postDetailPartial", oOffersInfo);
        }

        [HttpGet]
        public ActionResult NewPost()
        {
            oCurrentUser = (SysUser)Session["User"];
            var newPost = new OffersInfo();
            if (Session["User"] != null)
            {
                var enumFeature = Convert.ToInt32(Enumaretion.DBEnumType.OfferFeature);
                var lowFeature = oDBContext.SysEnums.FirstOrDefault(t => t.EnumType == enumFeature && t.EnumName.ToLower().Contains("low")).ID;
                oSysCurrentUser = (SysUser)Session["User"];
                newPost.OfferFeatureVal = lowFeature;
                newPost.IsActive = false;
                newPost.CreatedBy = oSysCurrentUser.ID;
                newPost.CreatedOn = DateTime.Now;
                newPost.OfferStatus = 1; //hardcode for offer status
                newPost.OfferStartDate = DateTime.Now;
                newPost.OfferEndDate = DateTime.Now;

                ViewBag.CatList = oDBContext.OfferCategories.Where(t => t.IsActive).Select(x => x).ToList().Select(x => new SelectListItem
                {
                    Value = x.ID.ToString(),
                    Text = x.CategoryName.ToString()
                });

                if (!IsCurrentUserAdmin())
                {
                    ViewBag.LocList = oDBContext.OfferLocOutletMaps.Where(t => t.IsActive && t.SysUser.ID == oCurrentUser.ID).Select(x => x.OfferLocation).Distinct().ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.LocationName.ToString()
                    });
                }
                else
                {
                    ViewBag.LocList = oDBContext.OfferLocOutletMaps.Where(t => t.IsActive).Select(x => x.OfferLocation).Distinct().ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.LocationName.ToString()
                    });
                }

                if (IsCurrentUserAdmin())
                {

                    ViewBag.FeatureList = oDBContext.SysEnums.Where(t => t.EnumType == enumFeature).Select(x => x).ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.EnumName.ToString()
                    });
                }
                else
                {
                    ViewBag.FeatureList = oDBContext.SysEnums.Where(t => t.EnumType == enumFeature  && t.EnumName.ToLower().Contains("low")).Select(x => x).ToList().Select(x => new SelectListItem
                    {
                        Value = x.ID.ToString(),
                        Text = x.EnumName.ToString()
                    });
                }

                return PartialView("_createPostPartial", newPost);
            }
            else
                return RedirectToAction("SignIn", "SignIn");
        }

        [HttpGet]
        public ActionResult GetAvailableOutletList(int OfferId, int LocId)
        {
            oCurrentUser = (SysUser)Session["User"];
            var availOutletList = new List<CatLocAvailableOutlet>();
            if (!IsCurrentUserAdmin())
            {
                availOutletList = oDBContext.OfferLocOutletMaps.Where(t => t.IsActive && t.LocationID == LocId && t.UserId == oCurrentUser.ID ).Select(t => new CatLocAvailableOutlet
                {
                    offerId = t.OfferAvailOutlets.FirstOrDefault().OfferId,
                    outletLocationId = t.LocationID,
                    outletId = t.ID,
                    outletName = t.OutletName,
                    outletAddress = t.OutletAddress,
                    outletLocation = t.OfferLocation.LocationName,
                    outletIsActive = (t.OfferAvailOutlets.FirstOrDefault(x => x.OfferId == OfferId && x.OutletID == t.ID) != null) ? true : false

                }).ToList();
            }
            else
            {
                var offerUserid = oDBContext.OffersInfoes.FirstOrDefault(t => t.ID == OfferId).SysUser.ID;
                availOutletList = oDBContext.OfferLocOutletMaps.Where(t => t.IsActive && t.LocationID == LocId && t.UserId == offerUserid).Select(t => new CatLocAvailableOutlet
                {
                    offerId = t.OfferAvailOutlets.FirstOrDefault(x => x.OfferId == OfferId).OfferId,
                    outletLocationId = t.LocationID,
                    outletId = t.ID,
                    outletName = t.OutletName,
                    outletAddress = t.OutletAddress,
                    outletLocation = t.OfferLocation.LocationName,
                    outletIsActive = (t.OfferAvailOutlets.FirstOrDefault(x => x.OfferId == OfferId && x.OutletID == t.ID) != null) ? true : false

                }).ToList();

                //availOutletList = oDBContext.OfferAvailOutlets.Where(t => t.IsActive && t.OfferLocOutletMap.LocationID == LocId).Select(t => new CatLocAvailableOutlet
                //{
                //    offerId = t.OfferId,
                //    outletLocationId = t.OfferLocOutletMap.LocationID,
                //    outletId = t.OfferLocOutletMap.ID,
                //    outletName = t.OfferLocOutletMap.OutletName,
                //    outletAddress = t.OfferLocOutletMap.OutletAddress,
                //    outletLocation = t.OfferLocOutletMap.OfferLocation.LocationName,
                //    outletIsActive = true

                //}).ToList();
            }
            return PartialView("_postLocOutletsPartial", availOutletList);
        }

        [HttpGet]
        public ActionResult GetMorePost(int pageNo, string[] CategoryId, string[] LocationId, string SearchWord, string[] PostStatus)
        {
            oCurrentUser = (SysUser)Session["User"];
            var morePostList = GetOffersInfo();
            if (morePostList != null && morePostList.Count > 0)
            {
                if (CategoryId != null && CategoryId.Count() > 0)
                    morePostList = morePostList.Where(t => CategoryId.Contains(t.OfferCat.ToString())).ToList();
                if (LocationId != null && LocationId.Count() > 0)

OfferWebSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Discount Buzz System BD">
    <meta name="keywords" content="Discount, Offer">
    <title>@ViewBag.Title</title>
    <!-- Favicons-->
    <link rel="icon" href="~/Content/ImageSys/favicon/favicon-32x32.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="~/Content/ImageSys/favicon/apple-touch-icon-152x152.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
    <!-- For Windows Phone -->
    <!-- CORE CSS-->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themeCSS/materialize.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="~/Content/themeCSS/style.css" type="text/css" rel="stylesheet" media="screen,projection">
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="~/Content/themeCSS/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="~/Content/themeCSS/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet">

    <link href="~/Content/bootstrap-rating/star-rating.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-rating/star-rating.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-fileinput/css/fileinput.css" rel="stylesheet" />

    <script type="text/javascript" src="~/Scripts/jquery-1.11.2.min.js"></script>
    @*<script src="~/Scripts/jquery-migrate.min.js" type="text/javascript"></script>*@
    <!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>

    <script src="~/Scripts/fileinput.js"></script>
    <script type="text/javascript">
        //$(document).ready(function () {
        //    $(document).on("click", "#btnNewPost", function () {
        //        var url = $(this).attr("data-url");

        //        $.get(url , function (data) {
        //            $('#modal-post-detail').html(data);
        //            //$.validator.unobtrusive.parse($('.modal-body'));
        //        });
        //    });
        //});
    </script>

</head>
<body>
    <!-- Start Page Loading -->
    <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
    </div>
    <!-- End Page Loading -->
    <header id="header" class="page-topbar">
        <!-- start header nav-->
        @if (Session["User"] != null)
        {
            Html.RenderAction("NavbarDetails", "Dashboard");
        }
    </header>
    

    <div id="main" class="col s12 m6 l3 centered" style="padding-left: 1%; width: 99%; position: absolute;">
        <!-- START WRAPPER -->
        <div class="wrapper">
            <!-- START LEFT SIDEBAR NAV-->
            @*<aside id="left-sidebar-nav">
                @if (Session["User"] != null)
                {
                    Html.RenderAction("MenuDetails", "Dashboard");
                }
            </aside>*@
            <section id="content">

                <!--start container-->
                @RenderBody()

            </section>
        </div>
    </div>
    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large red modal-trigger" id="btnNewPost" href="#modal1" data-url="@Url.Action("NewPost","Post")">
            <i class="large mdi-editor-mode-edit"></i>
        </a>
    </div>



    <!-- ================================================
      Scripts
      ================================================ -->
   


    <!--materialize js-->
    <script type="text/javascript" src="~/Scripts/materialize.js"></script>
    <!--prism-->
    <script type="text/javascript" src="~/Scripts/prism.js"></script>
    <!--scrollbar-->
    <script type="text/javascript" src="~/Scripts/plugin/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script type="text/javascript" src="~/Scripts/plugin/chartist-js/chartist.min.js"></script>
    <!--plugins.js - Some Specific JS codes for Plugin Settings-->
    <script type="text/javascript" src="~/Scripts/plugins.js"></script>

    <script src="~/Scripts/star-rating.js"></script>

    <script type="text/javascript" src="~/Scripts/Custom.js"></script>

    <div class="row center">
        @if (TempData["SuccessMsg"] != null)
        {
            <script type="text/javascript">
                Materialize.toast('@TempData["SuccessMsg"].ToString().Replace(@"\r\n", @"")', 4000)
            </script>
            @*<div class="card-panel light-green white-text">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    <strong><span class="fa fa-check"></span></strong>@TempData["SuccessMsg"].ToString()
                </div>*@
        }

        @if (TempData["ErrorMsg"] != null)
        {
            <script type="text/javascript">
                Materialize.toast('@TempData["ErrorMsg"].ToString()', 4000)
            </script>
            @*<div class="card-panel red white-text">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                    <strong><span class="fa  fa-times"></span></strong>@TempData["ErrorMsg"].ToString()
                </div>*@
        }

    </div>

    <div id="modal1" class="modal" tabindex="-1" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-header">
            <div class="row">
                <a href="#" style="float:right;" class="waves-effect waves-red btn-flat modal-action modal-close">Close</a>
            </div>
        </div>
        <div class="modal-content center" id="modal-post-loader">
            <div class="preloader-wrapper active">
                <div class="spinner-layer spinner-red-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="model-content" id="modal-post-detail" style="padding: 1%;">

        </div>
    </div>

</body>
</html>

OfferWebSystem/Views/Shared/_headerNavbarPartial.cshtml
@model OfferWebSystem.Models.UserMenuModel


<div class="navbar-fixed">
    <nav class="teal darken-2">
        <div class="nav-wrapper">
            <h1 class="logo-wrapper">
                <a href="@Url.Action("Index","Dashboard")" class="brand-logo darken-1"><img src="~/Content/ImageSys/materialize-logo.png" alt="materialize logo"></a>
                <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi-action-view-headline"></i></a>
                <span class="logo-text">Discount</span>
            </h1>
            <ul id="slide-out" class="side-nav">
                <li><img src="~/Content/ImageSys/materialize-logo.png" alt="materialize logo"></li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Index","Dashboard")" class="waves-effect waves-block waves-light"><i class="mdi-action-dashboard large"></i>Dashboard</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Index","Post")" class="waves-effect waves-block waves-light"><i class="mdi-maps-local-offer large"></i>Discount Post</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="@Url.Action("Index","Outlet")" class="waves-effect waves-light collection-item"><i class="mdi-action-store large"></i> Outlet</a>
                </li>
                <li class="divider"></li>
                @if (Model.UserDetail != null && Model.UserDetail.SysEnum.EnumName.ToLower().Contains("administrator"))
                {
                    <li>
                        <a href="@Url.Action("Index","Location")" class="waves-effect waves-light collection-item"><i class="mdi-maps-place large"></i> Location</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index","Category")" class="waves-effect waves-light collection-item"><i class="mdi-action-class large"></i> Category</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="@Url.Action("Index","User")" class="waves-effect waves-light collection-item"><i class="mdi-social-people large"></i>System Users</a>
                    </li>
                }
                <li class="divider"></li>
                <li>
                    <i class="mdi-action-face-unlock left green-text" style="margin-left: 1%;"></i>
                    <a href="@Url.Action("UserProfile","User")">Profile</a>
                </li>
                <li class="divider"></li>
                <li>
                    <i class="mdi-maps-directions left red-text" style="margin-left: 1%;"></i>
                    <a href="@Url.Action("LogOut","SignIn")" class="collection-item">Logout</a>
                </li>
            </ul>

            <ul class="right hide-on-med-and-down">

                <li>
                    <a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen tooltipped" data-position="bottom" data-delay="50" data-tooltip="Full Screen"><i class="mdi-action-settings-overscan"></i></a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Dashboard")" class="waves-effect waves-block waves-light tooltipped" data-position="bottom" data-delay="50" data-tooltip="Dashboard"><i class="mdi-action-dashboard large"></i></a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Post")" class="waves-effect waves-block waves-light tooltipped" data-position="bottom" data-delay="50" data-tooltip="Discount Post"><i class="mdi-maps-local-offer large"></i></a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Outlet")" class="waves-effect waves-light collection-item tooltipped" data-position="bottom" data-delay="50" data-tooltip="Outlet"><i class="mdi-action-store large"></i></a>
                </li>
                @if (Model.UserDetail != null && Model.UserDetail.SysEnum.EnumName.ToLower().Contains("administrator"))
                {
                    <li>
                        <a href="@Url.Action("Index","Location")" class="waves-effect waves-light collection-item tooltipped" data-position="bottom" data-delay="50" data-tooltip="Location"><i class="mdi-maps-place large"></i></a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Category")" class="waves-effect waves-light collection-item tooltipped" data-position="bottom" data-delay="50" data-tooltip="Category"><i class="mdi-action-class large"></i></a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","User")" class="waves-effect waves-light collection-item tooltipped" data-position="bottom" data-delay="50" data-tooltip="System Users"><i class="mdi-social-people large"></i></a>
                    </li>
                }

                <li>
                    <a class="dropdown-button white-text waves-effect waves-block waves-light" href="#!" data-activates="ddUserOption">@Model.UserDetail.UserId<i class="mdi-hardware-keyboard-arrow-down right"></i></a>
                </li>

            </ul>

        </div>
    </nav>
</div>
<!-- Dropdown Structure -->
<ul id="ddUserOption" class="dropdown-content collection">
    <li>
        <i class="mdi-action-face-unlock left green-text" style="margin-left: 1%;"></i>
        <a href="@Url.Action("UserProfile","User")">Profile</a>
    </li>
    <li class="divider"></li>
    <li>
        <i class="mdi-maps-directions left red-text" style="margin-left: 1%;"></i>
        <a href="@Url.Action("LogOut","SignIn")" class="collection-item">Logout</a>
    </li>
</ul>

<script type="text/javascript">
    $(document).ready(function () {
        $(".dropdown-button").dropdown({
            constrain_width: false
        });
        $(".button-collapse").sideNav();
        $('.tooltipped').tooltip({ delay: 50 });

    });

</script>