OfferWebSystem/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfferWebSystem.EFnClass;
using OfferWebSystem.Models;
using System.Web.Security;
using System.Threading.Tasks;
using System.IO;

namespace OfferWebSystem.Controllers
{
    public class SignInController : AppBaseController
    {
        //
        // GET: /SignIn/
        SysUser oSysUser = null;

        [AllowAnonymous]

        public ActionResult Index()
        {
            if (IsSessionExist())
                return RedirectToAction("Index", "Dashboard");
            else {
                Session.Clear();
                return View();
            }
        }

        public ActionResult ForgetPassword()
        {
            Session.Clear();
            return View();
        }
        [AllowAnonymous]
        public ActionResult Register()
        {
            Session.Clear();
            return View();
        }

        [AllowAnonymous]
        public ActionResult SignInSubmit(LogIn objSignIn)
        {
            if (ModelState.IsValid)
            {

                oSysUser = oDBContext.SysUsers.FirstOrDefault(t => t.UserId == objSignIn.USERID && t.Password == objSignIn.USERPASSWORD.Trim());
                if (Membership.ValidateUser(objSignIn.USERID, objSignIn.USERPASSWORD))
                {
                    FormsAuthentication.Authenticate(objSignIn.USERID, objSignIn.USERPASSWORD);
                    Session["User"] = oSysUser;
                    Session["UserRole"] = oSysUser.SysEnum.EnumName.ToLower().Trim();
                    oCurrentUserType = oSysUser.SysEnum.EnumName.ToLower().Trim();
                    oSysAdmin = (oSysUser.SysEnum.EnumName.ToLower().Trim().Contains("administrator")) ? true : false;
                    return RedirectToAction("Index", "Dashboard");
                }
                else
                {
                    TempData["SignMsg"] = "Invalid User ID / Password !!!";
                    return View("Index");
                }

            }

            return View("Index");
        }

        [AllowAnonymous]
        public ActionResult ForgetPasswordSubmit(ForgetPassword objFgtPwd)
        {
            if (ModelState.IsValid)
            {

                oSysUser = oDBContext.SysUsers.FirstOrDefault(t => t.UserId == objFgtPwd.USERID && t.Email == objFgtPwd.USEREMAIL.Trim());
                if (oSysUser != null)
                {
                    string body = string.Empty;
                    using (StreamReader reader = new StreamReader(HttpContext.Server.MapPath("~/Content/EmailTemplate/ForgetPasswordEmailBody.html")))
                    {
                        body = reader.ReadToEnd();
                    }
                    body = body.Replace("{UserID}", oSysUser.UserId);
                    body = body.Replace("{Email}", oSysUser.Email);
                    body = body.Replace("{Password}", oSysUser.Password);
                    SendEmail.SendMail("Forget Password", objFgtPwd.USEREMAIL, body);
                    TempData["SignMsgSuccess"] = "Please Check Inbox/Spam/Junk of your mailbox.";
                    return View("Index");
                }
                else
                {
                    TempData["SignMsg"] = "Invalid User ID / Email !!!";
                    return View("Index");
                }

            }

            return View("Index");
        }

        [AllowAnonymous]
        public ActionResult SignRegister(RegisterUser objRegisterUser)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var userRegister = oDBContext.SysUsers.FirstOrDefault(t => t.UserId == objRegisterUser.USERID);
                    if (userRegister == null)
                    {
                        int eType = Convert.ToInt32(Enumaretion.DBEnumType.SysUserType);
                        var standardUserType = oDBContext.SysEnums.FirstOrDefault(t => t.EnumType == eType && t.EnumName.ToLower().Contains("standard"));
                        SysUser oSysUser = new SysUser();
                        oSysUser.UserId = objRegisterUser.USERID;
                        oSysUser.Password = objRegisterUser.USERPASSWORD;
                        oSysUser.Email = objRegisterUser.USEREMAIL;
                        oSysUser.CompanyName = objRegisterUser.USERCOMPANY;
                        oSysUser.IsActive = true;
                        oSysUser.UserType = (standardUserType != null) ? standardUserType.ID : 2;
                        oSysUser.CreatedBy = 0;
                        oSysUser.CreatedOn = DateTime.Now;

                        oDBContext.SysUsers.Add(oSysUser);
                        oDBContext.SaveChanges();
                    }
                    else
                    {
                        TempData["SignMsg"] = "User already Exists!!!";
                        return View("Register");
                    }


                }
            }
            catch (Exception ex)
            {
                TempData["SignMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return View("Index");
        }
        public ActionResult LogOut(string Msg)
        {
            Session.Clear();
            return View("Index");
        }

        public ActionResult NotAuthorized()
        {
            TempData["SignMsg"] = "Not Authorized. Please Sign in again...";
            Session.Clear();
            return View("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult IsUserIDExists(string USERID)
        {

            var user = oDBContext.SysUsers.FirstOrDefault(t => t.UserId == USERID);

            return Json(user == null);
        }

    }
}

OfferWebSystem/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OfferWebSystem.Controllers
{
    public class WelcomeController : AppBaseController
    {
        // GET: Welcome
        public ActionResult Index()
        {
            if (IsSessionExist())
                return RedirectToAction("Index", "Dashboard");
            else {
                return View();
            }
        }
    }
}

OfferWebSystem/Views/Welcome/Index.cshtml
@{
    ViewBag.Title = "Discount Buzz";
    Layout = "~/Views/Shared/_LayoutWelcome.cshtml";
}

@*<nav class="white" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="#" class="brand-logo"><img src="~/Content/ImageSys/login-logo.png" alt="" class="circle responsive-img valign profile-image-login"></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="#">Navbar Link</a></li>
            </ul>
            <ul id="nav-mobile" class="side-nav">
                <li><a href="#">Navbar Link</a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>*@
<div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
        <div class="container">
            <br><br>
            <h1 class="header center teal-text text-lighten-2"><img src="~/Content/ImageSys/login-logo.png" alt="" class="circle responsive-img valign profile-image-login"> Discount Buzz</h1>
            <div class="row center">
                <h5 class="header col s12 light white-text">An innovative way to communicate your attractive packages with your targeted customer segment.</h5>
            </div>
            <div class="row center">
                <a href="@Url.Action("Index","SignIn")" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
            </div>
            <br><br>
        </div>
    </div>
    <div class="parallax"><img src="~/Content/ImageSys/background1.jpg" alt="Unsplashed background img 1"></div>
</div>

<div class="container">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center teal-text"><i class="mdi-action-help large"></i></h2>
                    <h5 class="center">What is Discount Buzz</h5>
                    <p class="light">Discount Buzz is an application for Android and IOS user to showcase all the available deals discounts and offers available around their city. Here you can post your offer/Discounts/Deals and that will directly be shown to all the users in their smartphone even on the go. You don’t have to spend tons of money for the perfect customer anymore whereas your desired customers will be informed about your promotion through the platform. They can even provide their opinion and feedback on your promotional offer whether they like it or not or what would make them happier. </p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center teal-text"><i class="mdi-action-favorite-outline large"></i></h2>
                    <h5 class="center">Why is Discount Buzz</h5>
                    <p class="light">
                        How much penny you have spent in your last promotional activity and do you know exact feedback of the campaign?
                        <br />
                        We are providing
                        <br />
                        Ø  Perfect medium for your campaign to directly connect with your desired customers.
                        <br />
                        Ø  Check the feedback.
                        <br />
                        Ø  Redesign your next promotion.
                        <br />
                        Ø  Statistical data for successful campaign.
                    </p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center teal-text"><i class="mdi-hardware-smartphone large"></i></h2>
                    <h5 class="center">Easy Interface</h5>
                    <p class="light">We have built a very user-friendly interface that will guide you through the steps required to post an offer and deal. Find insights about the deal’s activity and provide any required feedback to redesign any update you need. Customer end is also very interactive and easy to use which will draw many to use this app for a longer time. </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="~/Content/ImageSys/background2.jpg" alt="Unsplashed background img 2"></div>
</div>


<footer class="page-footer teal">
    @*<div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Company Bio</h5>
                    <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>

                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Settings</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                    </ul>
                </div>
                <div class="col l3 s12">
                    <h5 class="white-text">Connect</h5>
                    <ul>
                        <li><a class="white-text" href="#!">Link 1</a></li>
                        <li><a class="white-text" href="#!">Link 2</a></li>
                        <li><a class="white-text" href="#!">Link 3</a></li>
                        <li><a class="white-text" href="#!">Link 4</a></li>
                    </ul>
                </div>
            </div>
        </div>*@
</footer>