OfferWebSystem/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfferWebSystem.EFnClass;
using OfferWebSystem.Models;

namespace OfferWebSystem.Controllers
{
    [SessionExpire]
    [CustomAuthorize(Roles = "administrator")]
    public class LocationController : AppBaseController
    {
        // GET: Location
        public List<OfferLocation> oLocationList = null;
        public OfferLocation oOfferLocation = null;
        public ActionResult Index()
        {
            oCurrentUser = (SysUser)Session["User"];
            oLocationList = oDBContext.OfferLocations.ToList();
            return View(oLocationList);
        }

        [HttpGet]
        public ActionResult NewLocation()
        {
            oCurrentUser = (SysUser)Session["User"];
            var newLocation = new OfferLocation();
            newLocation.IsActive = false;
            var LocationInfo = new LocationDetailModel();
            LocationInfo.IsNew = true;
            LocationInfo.Location = newLocation;

            ViewBag.LocationList = oDBContext.OfferLocations.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.LocationName.ToString()
            });

            return PartialView("_locationDetailPartial", LocationInfo);
        }

        [HttpGet]
        public ActionResult UpdateLocation(int id)
        {

            var LocationInfo = new LocationDetailModel();
            LocationInfo.IsNew = false;
            LocationInfo.Location = oDBContext.OfferLocations.FirstOrDefault(t => t.ID == id);
            ViewBag.LocationList = oDBContext.OfferLocations.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.LocationName.ToString()
            });
            return PartialView("_locationDetailPartial", LocationInfo);
        }


        [HttpPost]
        public ActionResult InsertLocation(LocationDetailModel oLocationInfo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (SysUser)Session["User"];
                    var existLocation = oDBContext.OfferLocations.FirstOrDefault(t => t.ID == oLocationInfo.Location.ID);
                    if (existLocation == null)
                    {
                        OfferLocation oOfferLocation = oLocationInfo.Location;
                        oOfferLocation.IsActive = true;
                        oOfferLocation.CreatedBy = oCurrentUser.ID;
                        oOfferLocation.CreatedOn = DateTime.Now;
                        oDBContext.OfferLocations.Add(oOfferLocation);
                        oDBContext.SaveChanges();
                        TempData["SuccessMsg"] = "Data Saved Successfully";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Data already Exists!!!";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateLocation(LocationDetailModel oLocationInfo, string chkIsActive)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (SysUser)Session["User"];
                    var existLocation = oDBContext.OfferLocations.FirstOrDefault(t => t.ID == oLocationInfo.Location.ID);
                    if (existLocation != null)
                    {
                        existLocation.LocationName = oLocationInfo.Location.LocationName;
                        existLocation.ModifiedBy = oCurrentUser.ID;
                        existLocation.ModifiedOn = DateTime.Now;
                        existLocation.IsActive = (!string.IsNullOrEmpty(chkIsActive) && chkIsActive.Contains("on")) ? true : false;
                        oDBContext.SaveChanges();
                        TempData["SuccessMsg"] = "Data Update Successfully";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Data Not Found!!!";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }

    }
}

OfferWebSystem/Views/Location/Index.cshtml
@model List<OfferWebSystem.EFnClass.OfferLocation>
@{
    ViewBag.Title = "Location | Discount Buzz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="mail-app" class="section">

    <div class="row z-depth-1">

        <nav class="light-blue">
            <div class="nav-wrapper">
                <div class="left col s12 m6 l6">
                    <ul>
                        <li>
                            <i class="mdi-maps-place white-text"></i>
                        </li>
                        <li>
                            <h4 class="header"> Location</h4>
                        </li>
                    </ul>
                </div>
                <div class="col s12 m6 l6">
                    <ul class="right">
                        <li class="search-out">
                            <input type="text" class="search-out-text" id="location-search" data-url="@Url.Action("GetLocationByKeyword", "Location")">
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="waves-effect waves-block waves-light show-search"><i class="mdi-action-search"></i></a>
                        </li>
                        <li>
                            <a href="#modal1" data-url="@Url.Action("NewLocation", "Location")" id="newLocation" class="waves-effect waves-block waves-light modal-trigger"><i class="mdi-content-add-circle-outline left" style="margin-right:0"></i><i class="mdi-maps-place right" style="margin-left:0"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <hr />
        

        <div class="col-sm-12">
            <div class="preloader-wrapper center hide" id="location-list-loader">
                <div class="spinner-layer spinner-red-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <div class="row" id="location-list">
                @Html.Partial("_locationListPartial", Model)
            </div>
            <div class="divider"></div>

        </div>

    </div>
</div>

OfferWebSystem/Views/Location/_locationDetailPartial.cshtml
@model OfferWebSystem.Models.LocationDetailModel
@{
    var LocationObj = Model.Location;
}


<div class="">
    <span class="left transparent green-text large"><i class="mdi-maps-place"></i></span><h4 class="header">Location</h4>
    @if (Model.IsNew)
    {
        <div class="">

            @Html.AntiForgeryToken()
            @using (Html.BeginForm("InsertLocation", "Location", FormMethod.Post, new { @class = "form" }))
            {
                @Html.HiddenFor(m => m.Location.ID)
                @Html.HiddenFor(m => m.Location.CreatedBy)
                @Html.HiddenFor(m => m.Location.CreatedOn)
                @Html.HiddenFor(m => m.Location.ModifiedBy)
                @Html.HiddenFor(m => m.Location.ModifiedOn)

                <div class="col-sm-2 pull-right">
                    <button class="btn waves-effect waves-light right " type="submit" name="action">Save<i class="mdi-content-save left"></i></button>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l12">
                        <i class="mdi-action-receipt prefix"></i>
                        @Html.TextBoxFor(m => m.Location.LocationName, new { id = "LocationName", @class = "validate", placeholder = "Enter Location Name" })
                        <label for="LocationName" class="active">Location Name</label>
                        @Html.ValidationMessageFor(m => m.Location.LocationName, null, new { @class = "card-panel red display" })
                    </div>
                </div>

                @*<div class="row">
                        <div class="switch">
                            Active ?
                            @Html.CheckBoxFor(m => m.Location.IsActive, new { id="chkIsActive"})
                            @if (@Model.Location.IsActive)
                            {
                                <label>
                                    NO
                                    <input checked="checked" data-val="@Model.Location.IsActive" id="chkIsActive" name="LocationIsActive" type="checkbox">
                                    <span class="lever"></span> YES
                                </label>
                            }
                            else
                            {
                                <label>
                                    NO
                                    <input checked="checked" data-val="@Model.Location.IsActive" id="chkIsActive" name="LocationIsActive" type="checkbox">
                                    <span class="lever"></span> YES
                                </label>
                            }


                        </div>
                    </div>*@
            }
        </div>
    }
    else
    {
        <div id="profile-card-postdetail" style=" margin:0px" class="card">
            <div class="card-panel transparent lighten-2" style="margin:0px;">
                <span class="email-subject truncate card-title black-text caption">
                    @LocationObj.LocationName
                </span>
            </div>
            <div class="card-content">
                <a class="btn-floating activator btn-move-up waves-effect waves-light darken-2 right modal-trigger">
                    <i class="mdi-editor-mode-edit"></i>
                </a>
                <div class="email-content-wrap">

                    <hr />
                    <div class="col s12 m12 l12">
                        <h6 class="header"><b>Tagged Offer</b></h6>
                        @if (LocationObj.OffersInfoes != null && LocationObj.OffersInfoes.Count > 0)
                        {

                            var grid = new WebGrid(LocationObj.OffersInfoes, rowsPerPage: 10, canPage: false, canSort: false);


                            @grid.GetHtml(
                         tableStyle: "striped-table",
                         headerStyle: "flip-content",

                         columns: new[]{


                           grid.Column("PostName",header: "Post"),
                           grid.Column("OfferDiscountAmt",header: "Discount"),
                           grid.Column("OfferCategory.CategoryName",header: "Category")
                            },
                                                                             mode: WebGridPagerModes.All
                                                                             );
                        }
                        else
                        {
                            <div class="row">
                                <div class="card-panel red lighten-3 white-text">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                    <strong>Warning!</strong> No Offer Found!!!!
                                </div>
                            </div>
                        }
                    </div>
                    @if (!string.IsNullOrEmpty(Session["UserRole"].ToString()) && Session["UserRole"].ToString().ToLower().Contains("administrator"))
                    {
                        <div class="col-sm-12 data-credt-panel">
                            <div class="row">
                                <span class="teal-text black-text"><i class="mdi-action-assignment-ind"></i>Created By : @Model.Location.SysUser.UserId</span>
                                <span class="teal-text black-text"><i class="mdi-action-alarm-add"></i>Created On : @Model.Location.CreatedOn.ToString("dd-MMM-yyyy hh:mm:ss")</span>
                            </div>
                            @if (Model.Location.ModifiedBy.HasValue)
                            {
                                <div class="row">
                                    <span class="teal-text black-text"><i class="mdi-action-assignment-ind"></i>Modified By : @Model.Location.SysUser1.UserId</span>
                                    <span class="teal-text black-text"><i class="mdi-action-alarm-add"></i>Modified On :@Model.Location.ModifiedOn.Value.ToString("dd-MMM-yyyy hh:mm:ss")</span>
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
            <div class="card-reveal">
                @Html.AntiForgeryToken()
                @using (Html.BeginForm("UpdateLocation", "Location", FormMethod.Post, new { @class = "form" }))
                {
                    @Html.HiddenFor(m => m.Location.ID)
                    @Html.HiddenFor(m => m.Location.CreatedBy)
                    @Html.HiddenFor(m => m.Location.CreatedOn)
                    @Html.HiddenFor(m => m.Location.ModifiedBy)
                    @Html.HiddenFor(m => m.Location.ModifiedOn)
                    <span class="card-title grey-text text-darken-4"><i class="mdi-navigation-close right"></i></span>
                    <div class="col-sm-2 pull-right">
                        <button class="btn waves-effect waves-light right " type="submit" name="action">Save<i class="mdi-content-save left"></i></button>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m12 l12">
                            <i class="mdi-action-receipt prefix"></i>
                            @Html.TextBoxFor(m => m.Location.LocationName, new { id = "LocationName", @class = "validate", placeholder = "Enter Location Name" })
                            <label for="LocationName" class="active">Location Name</label>
                            @Html.ValidationMessageFor(m => m.Location.LocationName, null, new { @class = "card-panel red display" })
                        </div>
                    </div>


                    <div class="row">
                        <div class="switch">
                            <span class="caption"> <i class="mdi-action-verified-user"></i> Active </span>
                            @if (@Model.Location.IsActive)
                            {
                                <label>
                                    NO
                                    <input checked="checked" data-val="@Model.Location.IsActive" id="chkIsActive" name="chkIsActive" type="checkbox">
                                    <span class="lever"></span> YES
                                </label>
                            }
                            else
                            {
                                <label>
                                    NO
                                    <input data-val="@Model.Location.IsActive" id="chkIsActive" name="chkIsActive" type="checkbox">
                                    <span class="lever"></span> YES
                                </label>
                            }
                        </div>
                    </div>
                }
            </div>

        </div>
    }
</div>

OfferWebSystem/Views/Location/_locationListPartial.cshtml
@model List<OfferWebSystem.EFnClass.OfferLocation>

<div class="col s12 m12 l12">
    @if (Model != null && Model.Count > 0)
    {
        var grid = new WebGrid(Model, rowsPerPage: 10, canPage: true, canSort: false);
        @grid.GetHtml(
                         tableStyle: "table",
                         headerStyle: "flip-content",
                         alternatingRowStyle: "striped",
                         columns: new[]{
                             grid.Column(header: "Location Name",format:@<text><a class="editLocation modal-trigger" href="#modal1" data-id="@item.ID" data-url="@Url.Action("UpdateLocation", "Location")">@item.LocationName</a></text>),

                           grid.Column("IsActive", "Status",format: (item) => (item.IsActive) ? Html.Raw("<span class='mdi-action-done'></span>") : Html.Raw("<span class='mdi-action-highlight-remove'></span>"))
                         },
                        mode: WebGridPagerModes.All
                        );
    }
    else
    {
        <div class="row">
            <div class="card-panel red lighten-3 white-text">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                <strong>Warning!</strong> No Locations Found!!!!
            </div>
        </div>
    }
</div>