OfferWebSystem/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OfferWebSystem.EFnClass;
using OfferWebSystem.Models;
using System.IO;

namespace OfferWebSystem.Controllers
{
    [SessionExpire]
    [CustomAuthorize(Roles = "administrator")]
    public class CategoryController : AppBaseController
    {
        // GET: Category
        public List<OfferCategory> oCategoryList = null;
        public OfferCategory oOfferCategory = null;
        private static string postImagePath = "/Content/ImageCategory/";
        public ActionResult Index()
        {
            oCurrentUser = (SysUser)Session["User"];
            oCategoryList = oDBContext.OfferCategories.ToList();
            return View(oCategoryList);
        }

        [HttpGet]
        public ActionResult NewCategory()
        {
            oCurrentUser = (SysUser)Session["User"];
            var newCategory = new OfferCategory();
            newCategory.IsActive = false;

            var CategoryInfo = new CategoryDetailModel();
            CategoryInfo.IsNew = true;
            CategoryInfo.Category = newCategory;

            ViewBag.CategoryList = oDBContext.OfferCategories.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.CategoryName.ToString()
            });

            return PartialView("_categoryDetailPartial", CategoryInfo);
        }

        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {

            var CategoryInfo = new CategoryDetailModel();
            CategoryInfo.IsNew = false;
            CategoryInfo.Category = oDBContext.OfferCategories.FirstOrDefault(t => t.ID == id);

            ViewBag.CategoryList = oDBContext.OfferCategories.Select(x => x).ToList().Select(x => new SelectListItem
            {
                Value = x.ID.ToString(),
                Text = x.CategoryName.ToString()
            });

            return PartialView("_categoryDetailPartial", CategoryInfo);
        }


        [HttpPost]
        public ActionResult InsertCategory(CategoryDetailModel oCategoryInfo, HttpPostedFileBase ctrlCatIcon)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (SysUser)Session["User"];
                    var uploadFileName = "";
                    var existCategory = oDBContext.OfferCategories.FirstOrDefault(t => t.ID == oCategoryInfo.Category.ID);
                    if (existCategory == null)
                    {
                        OfferCategory oOfferCategory = oCategoryInfo.Category;
                        oOfferCategory.IsActive = true;
                        if (ctrlCatIcon != null)
                        {
                            uploadFileName = DateTime.Now.ToString("yyddMMhhmmssfff") + "_" + Path.GetFileName(ctrlCatIcon.FileName).Replace(" ", "").ToLower().Trim();
                            oOfferCategory.CategoryIcon = postImagePath + uploadFileName;
                            ctrlCatIcon.SaveAs(Path.Combine(Server.MapPath(postImagePath), uploadFileName));
                        }
                        oOfferCategory.CreatedBy = oCurrentUser.ID;
                        oOfferCategory.CreatedOn = DateTime.Now;
                        oDBContext.OfferCategories.Add(oOfferCategory);
                        oDBContext.SaveChanges();
                        TempData["SuccessMsg"] = "Data Saved Successfully";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Data already Exists!!!";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCategory(CategoryDetailModel oCategoryInfo, string chkIsActive, HttpPostedFileBase ctrlCatIcon)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    oCurrentUser = (SysUser)Session["User"];
                    var uploadFileName = "";
                    var existCategory = oDBContext.OfferCategories.FirstOrDefault(t => t.ID == oCategoryInfo.Category.ID);
                    if (existCategory != null)
                    {
                        existCategory.CategoryName = oCategoryInfo.Category.CategoryName;
                        if (ctrlCatIcon != null)
                        {
                            uploadFileName = DateTime.Now.ToString("yyddMMhhmmssfff") + "_" + Path.GetFileName(ctrlCatIcon.FileName).Replace(" ", "").ToLower().Trim();
                            existCategory.CategoryIcon = postImagePath + uploadFileName;
                            ctrlCatIcon.SaveAs(Path.Combine(Server.MapPath(postImagePath), uploadFileName));
                        }
                        existCategory.IsActive = (!string.IsNullOrEmpty(chkIsActive) && chkIsActive.Contains("on")) ? true : false;
                        existCategory.ModifiedBy = oCurrentUser.ID;
                        existCategory.ModifiedOn = DateTime.Now;
                        oDBContext.SaveChanges();
                        TempData["SuccessMsg"] = "Data Update Successfully";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Data Not Found!!!";
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = "Error Occured Due to " + ExceptionMsg(ex);
            }
            return RedirectToAction("Index");
        }

    }
}

OfferWebSystem/Views/Category/Index.cshtml
@model List<OfferWebSystem.EFnClass.OfferCategory>
@{
    ViewBag.Title = "Category | Discount Buzz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="mail-app" class="section">

    <div class="row z-depth-1">

        <nav class="light-blue">
            <div class="nav-wrapper">
                <div class="left col s12 m6 l6">
                    <ul>
                        <li>
                            <i class="mdi-action-class white-text"></i>
                        </li>
                        <li>
                            <h4 class="header"> Category</h4>
                        </li>
                    </ul>
                </div>
                <div class="col s12 m6 l6">
                    <ul class="right">
                        <li class="search-out">
                            <input type="text" class="search-out-text" id="Category-search" data-url="@Url.Action("GetCategoryByKeyword", "Category")">
                        </li>
                        <li>
                            <a href="javascript:void(0);" class="waves-effect waves-block waves-light show-search"><i class="mdi-action-search"></i></a>
                        </li>
                        <li>
                            <a href="#modal1" data-url="@Url.Action("NewCategory", "Category")" id="newCategory" class="waves-effect waves-block waves-light modal-trigger"><i class="mdi-content-add-circle-outline left" style="margin-right:0"></i><i class="mdi-action-class right" style="margin-left:0"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <hr />
        

        <div class="col-sm-12">
            <div class="preloader-wrapper center hide" id="category-list-loader">
                <div class="spinner-layer spinner-red-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <div class="row" id="category-list">
                @Html.Partial("_CategoryListPartial", Model)
            </div>
            <div class="divider"></div>

        </div>

    </div>
</div>

OfferWebSystem/Views/Category/_categoryDetailPartial.cshtml
@model OfferWebSystem.Models.CategoryDetailModel
@{
    var CategoryObj = Model.Category;
}


<div class="">
    <span class="left transparent green-text large"><i class="mdi-action-class"></i></span><h4 class="header">Category</h4>
    <div class="row">

        <div class="card-panel yellow lighten-4">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            <strong>Please!</strong> Width & Height of Category Icon Image should be equal.
        </div>
    </div>
    @if (Model.IsNew)
    {
        <div class="">

            @Html.AntiForgeryToken()
            @using (Html.BeginForm("InsertCategory", "Category", FormMethod.Post, new { @class = "form", enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(m => m.Category.ID)
                @Html.HiddenFor(m => m.Category.CreatedBy)
                @Html.HiddenFor(m => m.Category.CreatedOn)
                @Html.HiddenFor(m => m.Category.ModifiedBy)
                @Html.HiddenFor(m => m.Category.ModifiedOn)

                <div class="col-sm-2 pull-right">
                    <button class="btn waves-effect waves-light right " type="submit" name="action">Save<i class="mdi-content-save left"></i></button>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l12">
                        <i class="mdi-action-receipt prefix"></i>
                        @Html.TextBoxFor(m => m.Category.CategoryName, new { id = "CategoryName", @class = "validate", placeholder = "Enter Category Name" })
                        <label for="CategoryName" class="active">Category Name</label>
                        @Html.ValidationMessageFor(m => m.Category.CategoryName, null, new { @class = "card-panel red display" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <input id="ctrlCatIcon" name="ctrlCatIcon" type="file" multiple class="file-loading" data-preview-file-type="any" accept="image/*" />
                    </div>
                </div>

            }
        </div>
    }
    else
    {
        <div id="profile-card-postdetail" style=" margin:0px" class="card">
            <div class="card-panel transparent lighten-2" style="margin:0px;">
                <span class="email-subject truncate card-title black-text caption">
                    @CategoryObj.CategoryName
                </span>
            </div>
            <div class="card-content">

                <a class="btn-floating activator btn-move-up waves-effect waves-light darken-2 right modal-trigger">
                    <i class="mdi-editor-mode-edit"></i>
                </a>
                <div class="row">
                    @if (!string.IsNullOrEmpty(Model.Category.CategoryIcon) && File.Exists(Server.MapPath(Model.Category.CategoryIcon)))
                    {
                        <img class="materialboxed" src="@Model.Category.CategoryIcon" alt="sample" data-caption="@Model.Category.CategoryName">
                        <p></p>
                    }
                </div>

                <div class="email-content-wrap">

                    <hr />
                    <div class="col s12 m12 l12">
                        <h6 class="header"><b>Tagged Offer</b></h6>
                        @if (CategoryObj.OffersInfoes != null && CategoryObj.OffersInfoes.Count > 0)
                        {

                            var grid = new WebGrid(CategoryObj.OffersInfoes, rowsPerPage: 10, canPage: false, canSort: false);


                            @grid.GetHtml(
                         tableStyle: "striped-table",
                         headerStyle: "flip-content",

                         columns: new[]{


                           grid.Column("PostName",header: "Post"),
                           grid.Column("OfferDiscountAmt",header: "Discount"),
                           grid.Column("OfferCategory.CategoryName",header: "Category")
                            },
                                                                             mode: WebGridPagerModes.All
                                                                             );
                        }
                        else
                        {
                            <div class="row">
                                <div class="card-panel red lighten-3 white-text">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                                    <strong>Warning!</strong> No Offer Found!!!!
                                </div>
                            </div>
                        }
                    </div>
                    @if (!string.IsNullOrEmpty(Session["UserRole"].ToString()) && Session["UserRole"].ToString().ToLower().Contains("administrator"))
                    {
                        <div class="col-sm-12 data-credt-panel">
                            <div class="row">
                                <span class="teal-text black-text"><i class="mdi-action-assignment-ind"></i>Created By : @Model.Category.SysUser.UserId</span>
                                <span class="teal-text black-text"><i class="mdi-action-alarm-add"></i>Created On : @Model.Category.CreatedOn.ToString("dd-MMM-yyyy hh:mm:ss")</span>
                            </div>
                            @if (Model.Category.ModifiedBy.HasValue)
                            {
                                <div class="row">
                                    <span class="teal-text black-text"><i class="mdi-action-assignment-ind"></i>Modified By : @Model.Category.SysUser1.UserId</span>
                                    <span class="teal-text black-text"><i class="mdi-action-alarm-add"></i>Modified On :@Model.Category.ModifiedOn.Value.ToString("dd-MMM-yyyy hh:mm:ss")</span>
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
            <div class="card-reveal">
                @Html.AntiForgeryToken()
                @using (Html.BeginForm("UpdateCategory", "Category", FormMethod.Post, new { @class = "form", enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(m => m.Category.ID)
                    @Html.HiddenFor(m => m.Category.CreatedBy)
                    @Html.HiddenFor(m => m.Category.CreatedOn)
                    @Html.HiddenFor(m => m.Category.ModifiedBy)
                    @Html.HiddenFor(m => m.Category.ModifiedOn)
                    <span class="card-title grey-text text-darken-4"><i class="mdi-navigation-close right"></i></span>
                    <div class="col-sm-2 pull-right">
                        <button class="btn waves-effect waves-light right " type="submit" name="action">Save<i class="mdi-content-save left"></i></button>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m12 l12">
                            <i class="mdi-action-receipt prefix"></i>
                            @Html.TextBoxFor(m => m.Category.CategoryName, new { id = "CategoryName", @class = "validate", placeholder = "Enter Category Name" })
                            <label for="CategoryName" class="active">Category Name</label>
                            @Html.ValidationMessageFor(m => m.Category.CategoryName, null, new { @class = "card-panel red display" })
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-md-12">
                            <input id="ctrlCatIcon" name="ctrlCatIcon" type="file" multiple class="file-loading" data-preview-file-type="any" accept="image/*" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="switch">
                            <span class="caption"> <i class="mdi-action-verified-user"></i> Active </span>
                            @if (@Model.Category.IsActive)
                            {
                                <label>
                                    NO
                                    <input checked="checked" data-val="@Model.Category.IsActive" id="chkIsActive" name="chkIsActive" type="checkbox">
                                    <span class="lever"></span> YES
                                </label>
                            }
                            else
                            {
                                <label>
                                    NO
                                    <input data-val="@Model.Category.IsActive" id="chkIsActive" name="chkIsActive" type="checkbox">
                                    <span class="lever"></span> YES
                                </label>
                            }
                        </div>
                    </div>
                }
            </div>

        </div>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var imagePost;
        var imgPath = '@Model.Category.CategoryIcon';
        if (imgPath != '') {
            $.ajax({
                url: '@Model.Category.CategoryIcon',
                success: function (data, textStatus) {
                    imagePost = true;

                    $("#ctrlCatIcon").fileinput({
                        initialPreviewShowDelete: true,
                        overwriteInitial: true,
                        initialPreview: [
                            "<img src='@Model.Category.CategoryIcon' class='file-preview-image' alt='PostImage'>"
                        ],
                        dataType: 'json',
                        uploadAsync: false,
                        previewFileType: "image",
                        browseClass: "btn btn-success",
                        browseLabel: "Pick Image",
                        browseIcon: '<i class="glyphicon glyphicon-picture"></i>',
                        removeClass: "btn btn-danger",
                        removeLabel: "Delete",
                        removeIcon: '<i class="glyphicon glyphicon-trash"></i>',
                        showUpload: false,
                        uploadClass: "btn btn-info",
                        uploadLabel: "Upload",
                        uploadIcon: '<i class="glyphicon glyphicon-upload"></i>',
                        allowedFileExtensions: ["jpg", "gif", "png"],
                        maxImageWidth: 100,
                        maxImageHeight: 100,
                        maxFileCount: 1

                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    imagePost = false;

                    $("#ctrlCatIcon").fileinput({
                        previewFileType: "image",
                        browseClass: "btn btn-success",
                        browseLabel: "Pick Image",
                        browseIcon: '<i class="glyphicon glyphicon-picture"></i>',
                        removeClass: "btn btn-danger",
                        removeLabel: "Delete",
                        removeIcon: '<i class="glyphicon glyphicon-trash"></i>',
                        showUpload: false,
                        uploadClass: "btn btn-info",
                        uploadLabel: "Upload",
                        uploadIcon: '<i class="glyphicon glyphicon-upload"></i>',
                        allowedFileExtensions: ["jpg", "gif", "png"],
                        maxImageWidth: 100,
                        maxImageHeight: 100,
                        maxFileCount: 1

                    });
                }
            });
        }
        else {
            $("#ctrlCatIcon").fileinput({
                previewFileType: "image",
                browseClass: "btn btn-success",
                browseLabel: "Pick Image",
                browseIcon: '<i class="glyphicon glyphicon-picture"></i>',
                removeClass: "btn btn-danger",
                removeLabel: "Delete",
                removeIcon: '<i class="glyphicon glyphicon-trash"></i>',
                showUpload: false,
                uploadClass: "btn btn-info",
                uploadLabel: "Upload",
                uploadIcon: '<i class="glyphicon glyphicon-upload"></i>',
                allowedFileExtensions: ["jpg", "gif", "png"],
                maxImageWidth: 100,
                maxImageHeight: 100,
                maxFileCount: 1

            });
        }


    });
</script>

OfferWebSystem/Views/Category/_categoryListPartial.cshtml
@model List<OfferWebSystem.EFnClass.OfferCategory>

<div class="col s12 m12 l12">
    @if (Model != null && Model.Count > 0)
    {
        var grid = new WebGrid(Model, rowsPerPage: 10, canPage: true, canSort: false);
        @grid.GetHtml(
                         tableStyle: "table",
                         headerStyle: "flip-content",
                              alternatingRowStyle: "striped",
                         columns: new[]{
                             grid.Column(header: "Category Name",format:@<text><a  class="editCategory modal-trigger" href="#modal1" data-id="@item.ID" data-url="@Url.Action("UpdateCategory", "Category")">@item.CategoryName</a></text>),

                           grid.Column("IsActive", "Status",format: (item) => (item.IsActive) ? Html.Raw("<span class='mdi-action-done'></span>") : Html.Raw("<span class='mdi-action-highlight-remove'></span>"))
                         },
                                                              mode: WebGridPagerModes.All
                                                              );
    }
    else
    {
        <div class="row">
            <div class="card-panel red lighten-3 white-text">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                <strong>Warning!</strong> No Categorys Found!!!!
            </div>
        </div>
    }
</div>